//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM01
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitLeaders
    {
        public int ID { get; set; }
        public Nullable<int> Leader { get; set; }
        public int Unit { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Units Units { get; set; }
    }
}
